accounts:
  requestSchemaPath: "/schema/transferRequest.json"
  responseSchemaPath: "/schema/transferResponse.json"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
    initialization-mode: always
    hikari:
          connection-init-sql:
  jpa:
    generate-ddl: true



